//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Management_U48GFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public string Symbol { get; set; }
        public string Name { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Totalcost { get; set; }
    }
}
