//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Management_U48GFT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StocksDBEntities : DbContext
    {
        public StocksDBEntities()
            : base("name=StocksDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<Stocks_all> Stocks_all { get; set; }
        public virtual DbSet<Stocks_raw> Stocks_raw { get; set; }
        public virtual DbSet<tanar> tanars { get; set; }
        public virtual DbSet<user1> user1 { get; set; }
        public virtual DbSet<user2> user2 { get; set; }
    }
}
