//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Management_U48GFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks_raw
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Fent { get; set; }
        public Nullable<double> Lent { get; set; }
        public Nullable<double> Nyitas { get; set; }
        public Nullable<double> Zaras { get; set; }
        public Nullable<long> Volume { get; set; }
        public Nullable<double> Adj_Close { get; set; }
        public string OriginalFile { get; set; }
    }
}
